### ISSUE TITLE
RFE: recursive directory monitoring

### ISSUE THREAD

**Issue by borisovg** [snobb/imk#1]
It would be good to be able to watch a directory recursively. Currently something like this is necessry:

```imk -c 'make test' $(find modules tests/spec -type d)```

**Comment by snobb** [comment]
Added -r flag. If specified name is a directory - it will add all its subfolders as well (ignoring .git and .hg folders).

**Comment by snobb** [comment]
Looks like it was not pushed - will make sure it’s pushed ASAP.
